# Generated by Django 4.1.7 on 2023-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adsid',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
